#!/bin/sh
### BEGIN INIT INFO
# Provides:             moci-startup
# Required-Start:       $syslog $time $local-fs
# Required-Stop:
# Default-Start:        S
# Default-Stop:
### END INIT INFO

echo "Starting up MOCI scripts:" > /dev/kmsg
mkdir /home/root/out
python3 /usr/bin/api/controller.py &
telegraf &
